version: '2'
services:
  backend:

#    build: .
    image: duongk22899/home-stay:v2
    command: bash -c "./wait-for-it.sh db:5432 &&sequelize db:migrate && npm start"
    volumes:
      - ./:/usr/src/app/
    ports:
      - "3002:3001"
    depends_on:
      - db
#    environment:
#      DATABASE_URL: postgres://username:pgpassword@db:5432/homestay
#      WAIT_HOSTS: db:5432
    links:
      - db
  db:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_DB: homestay
      POSTGRES_PASSWORD: pgpassword