version: 2
jobs:
  build-home-stay:
    docker:
      - image: google/cloud-sdk:alpine
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            curl -fSL "https://get.docker.com/builds/Linux/x86_64/docker-17.03.0-ce.tgz" -o docker.tgz
            tar -xzvf docker.tgz
            mv docker/* /usr/local/bin/
            rmdir docker
            rm docker.tgz
            docker -v
      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKER_REGISTRY/home-stay:$CIRCLE_SHA1 .
      - run:
          name: Push Docker Image to DockerHub
          command: |
            docker login -u $HUB_ACCOUNT -p $HUB_PASS
            docker push $DOCKER_REGISTRY/home-stay:$CIRCLE_SHA1
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-home-stay